# Generated by Django 4.1.3 on 2022-12-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_uruns_urun_yenifiyat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uruns',
        ),
        migrations.RenameField(
            model_name='urun',
            old_name='fiyat',
            new_name='eskiFiyat',
        ),
        migrations.RenameField(
            model_name='urun',
            old_name='urunAdi',
            new_name='marka',
        ),
        migrations.RenameField(
            model_name='urun',
            old_name='aciklama',
            new_name='urunAciklama',
        ),
        migrations.AddField(
            model_name='urun',
            name='urunResmi',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
