# Generated by Django 4.1.3 on 2022-12-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_delete_uruns_rename_fiyat_urun_eskifiyat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='urunResmi',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
