# Generated by Django 4.1.3 on 2022-12-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_alter_urun_urunresmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='urunResmi',
            field=models.FileField(blank=True, null=True, upload_to='urunler/'),
        ),
    ]
