# Generated by Django 4.1.3 on 2022-12-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_urun_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='urun',
            name='altKategori',
            field=models.ManyToManyField(to='urunler.altkategori'),
        ),
    ]
